### PR TITLE
aph/pup-9307-mount-trailing-slashes

### PR DESCRIPTION
**Pull request by m0dular**

### CODE REVIEW

**Review by caseywilliams — APPROVED** [review]
Thanks for this PR -- This makes sense to me, and the tests all pass, but I'll wait for a second reviewer to merge.

**Comment by m0dular** [comment]
Much appreciated.  I did have a couple of questions for any reviewers.

Should I make another PR targeting 5.5.x or another version that sill has this in the `puppet` repo?  The customer that requested this is still on 5 and may not want to wait for an agent release.  The code looks mostly the same so I think I can do this.

As I mentioned in the comments, the acceptance test is "cheating".  The reason is that `puppet resource mount` behaves differently and I couldn't figure out why or if it should be changed.  If you have `/tmp/foo` mounted, `puppet resource mount /tmp/foo/` will not find this resource, with and without this patch.  I don't know how important this is, but it's something I noticed.

**Comment by mcdonaldseanp** [comment]
@sensei-de-loafage Yes, if the customer needs changes in the 5 series of the agent we'll have to also make these changes there.

**Review by mcdonaldseanp — APPROVED** [review]

**Comment by mcdonaldseanp** [comment]
@sensei-de-loafage if you could open a modules ticket for the weird puppet resource mount behavior we can properly triage and discuss the issue there.

**Comment by ScottGarman** [comment]
:+1:

**Pull request merged**
